 services:       
  bus-rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
      
  redis.cache:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"